# .github/workflows/python-talosbdd.yaml
name: talosbdd runner all test
on:
  workflow_dispatch:

jobs:
  test_linux_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Software
        run: sudo apt-get install -y chromium-browser

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Talos Web
        run: |
          python talos_run.py -t "san_web" -D Config_environment='chrome'

      - name: Save Execution Reports
        uses: actions/upload-artifact@v3
        with:
          name: reports-web
          path: |
            output

      - name: Run Talos Api
        run: |
          python talos_run.py -t "pokemon" -D Config_environment='backend'

      - name: Save Execution Reports
        uses: actions/upload-artifact@v3
        with:
          name: reports-api
          path: |
            output